# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import binja_pb2 as binja__pb2


class BinjaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestCycleCounts = channel.unary_unary(
                '/Binja/RequestCycleCounts',
                request_serializer=binja__pb2.BinjaInstructions.SerializeToString,
                response_deserializer=binja__pb2.CycleCounts.FromString,
                )


class BinjaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestCycleCounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BinjaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestCycleCounts': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestCycleCounts,
                    request_deserializer=binja__pb2.BinjaInstructions.FromString,
                    response_serializer=binja__pb2.CycleCounts.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Binja', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Binja(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestCycleCounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Binja/RequestCycleCounts',
            binja__pb2.BinjaInstructions.SerializeToString,
            binja__pb2.CycleCounts.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
